package agentkit

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// The wrapper exists to make installs survive a fresh server: the PATH the
// profile never set, the npm prefix a non-root user cannot write, the registry
// some networks cannot reach. Each of those protections has to actually be in
// the emitted script.
func TestInstallScriptWrapsForFreshServers(t *testing.T) {
	tool, _ := ByID("codex")
	npm, ok := MethodByID(tool, "npm")
	if !ok {
		t.Fatal("codex has no npm method to wrap")
	}
	s := MethodScript("Codex CLI via npm (global)", npm)

	if !strings.Contains(s, `"$HOME/.local/bin"`) {
		t.Error("PATH prelude missing: a runtime installed into $HOME would be invisible")
	}
	if !strings.Contains(s, `npm config set prefix "$HOME/.npm-global"`) {
		t.Error("npm prefix guard missing: non-root installs with system node fail with EACCES")
	}
	if !strings.Contains(s, "--registry="+npmMirror) {
		t.Error("registry fallback missing: servers behind restricted networks fail every npm install")
	}
	if !strings.Contains(s, "install FAILED (exit ") || !strings.Contains(s, "install finished OK") {
		t.Error("outcome banner missing: the pane would not say whether the install worked")
	}
	if !strings.Contains(s, `exec "${SHELL:-/bin/sh}" -l`) {
		t.Error("trailing shell missing: the window would close and take the output with it")
	}
}

func TestInstallScriptWithoutNpmSkipsNpmMachinery(t *testing.T) {
	tool, _ := ByID("claude-code")
	native, _ := MethodByID(tool, "native")
	s := MethodScript("Claude Code via Native installer", native)
	if strings.Contains(s, "npm config set prefix") || strings.Contains(s, npmMirror) {
		t.Error("npm-specific handling leaked into a non-npm install")
	}
}

// Labels reach the script inside single-quoted echo banners, and the custom
// install path lets the user type them.
func TestInstallScriptNeutralisesHostileLabels(t *testing.T) {
	s := InstallScript("x'; rm -rf /; echo '", "true")
	if strings.Contains(s, "rm -rf /; echo") && strings.Contains(s, "'; rm") {
		t.Error("label quoting can be broken out of")
	}
	if strings.Contains(s, "\rtrick") || strings.Contains(bannerSafe("a\r\nb'c\\d"), "'") {
		t.Error("bannerSafe left a quote or control character in place")
	}
	if got := bannerSafe("a\r\nb'c\\d"); got != "abcd" {
		t.Errorf("bannerSafe: got %q want %q", got, "abcd")
	}
}

// The wrapper is generated by string concatenation and the catalogue's own
// scripts are multi-line shell, so one misplaced quote breaks an install with
// a syntax error nobody sees until a server needs it. A real shell parses
// every method in the catalogue, plus the custom-script path.
func TestEveryInstallScriptParsesAsShell(t *testing.T) {
	sh, err := exec.LookPath("sh")
	if err != nil {
		t.Skip("no sh on this host")
	}
	scripts := map[string]string{
		"custom": InstallScript("custom install", "curl -fsSL https://example.test/i | bash"),
	}
	for _, tool := range All() {
		for _, m := range tool.Methods {
			scripts[tool.ID+"/"+m.ID] = MethodScript(tool.Name+" via "+m.Label, m)
		}
	}
	for name, script := range scripts {
		f := filepath.Join(t.TempDir(), "s.sh")
		if err := os.WriteFile(f, []byte(script), 0o600); err != nil {
			t.Fatal(err)
		}
		if out, err := exec.Command(sh, "-n", f).CombinedOutput(); err != nil {
			t.Errorf("%s does not parse: %v\n%s", name, err, out)
		}
	}
}

func TestCatalogIncludesGrok(t *testing.T) {
	tool, ok := ByID("grok")
	if !ok {
		t.Fatal("grok missing from the catalogue")
	}
	if tool.Binary != "grok" || tool.RunCommand != "grok" {
		t.Errorf("grok binary/run command wrong: %q / %q", tool.Binary, tool.RunCommand)
	}
	if _, ok := MethodByID(tool, "native"); !ok {
		t.Error("grok has no native install method")
	}
	if _, ok := MethodByID(tool, "npm"); !ok {
		t.Error("grok has no npm install method")
	}
}

// Docker is installed for the same reason as tmux — the work does not happen
// without it — and the same two things break it on the user's servers: a
// blocked download host, and a daemon the installer leaves stopped behind a
// group the user is not in.
func TestDockerInstallSurvivesAFreshServer(t *testing.T) {
	tool, ok := ByID("docker")
	if !ok {
		t.Fatal("docker missing from the catalogue")
	}
	if tool.Kind != "runtime" || tool.Binary != "docker" {
		t.Errorf("docker catalogued wrong: kind %q binary %q", tool.Kind, tool.Binary)
	}
	script, ok := MethodByID(tool, "script")
	if !ok {
		t.Fatal("docker has no official-script method")
	}
	if !strings.Contains(script.Retry, "--mirror Aliyun") {
		t.Error("no mirror fallback: the official script times out on restricted networks")
	}
	s := MethodScript("Docker via Official script", script)
	if !strings.Contains(s, "--mirror Aliyun") {
		t.Error("the wrapper dropped the mirror retry")
	}
	for _, m := range tool.Methods {
		if m.ID == "brew" { // Docker Desktop starts itself and has no docker group.
			continue
		}
		if !strings.Contains(m.Script, "usermod -aG docker") {
			t.Errorf("method %q leaves the user out of the docker group", m.ID)
		}
		if !strings.Contains(m.Script, "[ $drc -eq 0 ] || exit $drc") {
			t.Errorf("method %q reports success even when the install failed", m.ID)
		}
	}
}
