package agentkit

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// The wrapper exists to make installs survive a fresh server: the PATH the
// profile never set, the npm prefix a non-root user cannot write, the registry
// some networks cannot reach. Each of those protections has to actually be in
// the emitted script.
func TestInstallScriptWrapsForFreshServers(t *testing.T) {
	s := InstallScript("Codex CLI via npm (global)", "npm install -g @openai/codex", true)

	if !strings.Contains(s, `"$HOME/.local/bin"`) {
		t.Error("PATH prelude missing: a runtime installed into $HOME would be invisible")
	}
	if !strings.Contains(s, `npm config set prefix "$HOME/.npm-global"`) {
		t.Error("npm prefix guard missing: non-root installs with system node fail with EACCES")
	}
	if !strings.Contains(s, "--registry="+npmMirror) {
		t.Error("registry fallback missing: servers behind restricted networks fail every npm install")
	}
	if !strings.Contains(s, "install FAILED (exit ") || !strings.Contains(s, "install finished OK") {
		t.Error("outcome banner missing: the pane would not say whether the install worked")
	}
	if !strings.Contains(s, `exec "${SHELL:-/bin/sh}" -l`) {
		t.Error("trailing shell missing: the window would close and take the output with it")
	}
}

func TestInstallScriptWithoutNpmSkipsNpmMachinery(t *testing.T) {
	s := InstallScript("Claude Code via Native installer", "curl -fsSL https://claude.ai/install.sh | bash", false)
	if strings.Contains(s, "npm config set prefix") || strings.Contains(s, npmMirror) {
		t.Error("npm-specific handling leaked into a non-npm install")
	}
}

// Labels reach the script inside single-quoted echo banners, and the custom
// install path lets the user type them.
func TestInstallScriptNeutralisesHostileLabels(t *testing.T) {
	s := InstallScript("x'; rm -rf /; echo '", "true", false)
	if strings.Contains(s, "rm -rf /; echo") && strings.Contains(s, "'; rm") {
		t.Error("label quoting can be broken out of")
	}
	if strings.Contains(s, "\rtrick") || strings.Contains(bannerSafe("a\r\nb'c\\d"), "'") {
		t.Error("bannerSafe left a quote or control character in place")
	}
	if got := bannerSafe("a\r\nb'c\\d"); got != "abcd" {
		t.Errorf("bannerSafe: got %q want %q", got, "abcd")
	}
}

// The wrapper is generated by string concatenation, so one misplaced quote
// breaks every install at once. A real shell parses both variants here.
func TestInstallScriptParsesAsShell(t *testing.T) {
	sh, err := exec.LookPath("sh")
	if err != nil {
		t.Skip("no sh on this host")
	}
	for name, script := range map[string]string{
		"npm":   InstallScript("Codex CLI via npm (global)", "npm install -g @openai/codex", true),
		"plain": InstallScript("Claude Code via Native installer", "curl -fsSL https://claude.ai/install.sh | bash", false),
	} {
		f := filepath.Join(t.TempDir(), name+".sh")
		if err := os.WriteFile(f, []byte(script), 0o600); err != nil {
			t.Fatal(err)
		}
		if out, err := exec.Command(sh, "-n", f).CombinedOutput(); err != nil {
			t.Errorf("%s variant does not parse: %v\n%s", name, err, out)
		}
	}
}

func TestCatalogIncludesGrok(t *testing.T) {
	tool, ok := ByID("grok")
	if !ok {
		t.Fatal("grok missing from the catalogue")
	}
	if tool.Binary != "grok" || tool.RunCommand != "grok" {
		t.Errorf("grok binary/run command wrong: %q / %q", tool.Binary, tool.RunCommand)
	}
	if _, ok := MethodByID(tool, "native"); !ok {
		t.Error("grok has no native install method")
	}
	if _, ok := MethodByID(tool, "npm"); !ok {
		t.Error("grok has no npm install method")
	}
}
